# -----------
# -- Build --
# -----------

start:
	npm start

build:
	./node_modules/.bin/tsc

watch:
	./node_modules/.bin/tsc -w

# ------------
# -- Google --
# ------------

# .PHONY: deploy log describe browse
#
# deploy: build
# 	gcloud app deploy app.yaml cron.yaml
#
# log:
# 	gcloud app logs tail
#
# describe:
# 	gcloud projects describe wroclive
#
# browse:
# 	gcloud app browse
