# See:
# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

runtime: nodejs12
instance_class: F1

automatic_scaling:
  max_instances: 0 # disable

handlers:
- url: /.*
  script: auto
  secure: always
