import { Line } from '../models';
import { LinesProvider } from './LinesProvider';
import { Timestamped } from '../models';

export class DummyLineProvider implements LinesProvider {

  getLines(): Promise<Timestamped<Line[]>> {
    const timestamp = new Date().toISOString();
    const data = DummyLineProvider.data;
    return Promise.resolve({ timestamp, data });
  }

  static data: Line[] = [
    { name: 'A', type: 'Bus', subtype: 'Express' },
    { name: 'C', type: 'Bus', subtype: 'Express' },
    { name: 'D', type: 'Bus', subtype: 'Express' },
    { name: 'K', type: 'Bus', subtype: 'Express' },
    { name: 'N', type: 'Bus', subtype: 'Express' },
    { name: '0P', type: 'Tram', subtype: 'Regular' },
    { name: '0L', type: 'Tram', subtype: 'Regular' },
    { name: '1', type: 'Tram', subtype: 'Regular' },
    { name: '2', type: 'Tram', subtype: 'Regular' },
    { name: '3', type: 'Tram', subtype: 'Regular' },
    { name: '4', type: 'Tram', subtype: 'Regular' },
    { name: '5', type: 'Tram', subtype: 'Regular' },
    { name: '6', type: 'Tram', subtype: 'Regular' },
    { name: '7', type: 'Tram', subtype: 'Regular' },
    { name: '8', type: 'Tram', subtype: 'Regular' },
    { name: '9', type: 'Tram', subtype: 'Regular' },
    { name: '10', type: 'Tram', subtype: 'Regular' },
    { name: '11', type: 'Tram', subtype: 'Regular' },
    { name: '15', type: 'Tram', subtype: 'Regular' },
    { name: '16', type: 'Tram', subtype: 'Regular' },
    { name: '17', type: 'Tram', subtype: 'Regular' },
    { name: '20', type: 'Tram', subtype: 'Regular' },
    { name: '23', type: 'Tram', subtype: 'Regular' },
    { name: '31', type: 'Tram', subtype: 'Regular' },
    { name: '32', type: 'Tram', subtype: 'Regular' },
    { name: '33', type: 'Tram', subtype: 'Regular' },
    { name: '100', type: 'Bus', subtype: 'Regular' },
    { name: '101', type: 'Bus', subtype: 'Regular' },
    { name: '102', type: 'Bus', subtype: 'Regular' },
    { name: '103', type: 'Bus', subtype: 'Regular' },
    { name: '104', type: 'Bus', subtype: 'Regular' },
    { name: '105', type: 'Bus', subtype: 'Regular' },
    { name: '106', type: 'Bus', subtype: 'Regular' },
    { name: '107', type: 'Bus', subtype: 'Regular' },
    { name: '108', type: 'Bus', subtype: 'Regular' },
    { name: '109', type: 'Bus', subtype: 'Regular' },
    { name: '110', type: 'Bus', subtype: 'Regular' },
    { name: '111', type: 'Bus', subtype: 'Regular' },
    { name: '112', type: 'Bus', subtype: 'Regular' },
    { name: '113', type: 'Bus', subtype: 'Regular' },
    { name: '114', type: 'Bus', subtype: 'Regular' },
    { name: '115', type: 'Bus', subtype: 'Regular' },
    { name: '116', type: 'Bus', subtype: 'Regular' },
    { name: '118', type: 'Bus', subtype: 'Regular' },
    { name: '119', type: 'Bus', subtype: 'Regular' },
    { name: '120', type: 'Bus', subtype: 'Regular' },
    { name: '121', type: 'Bus', subtype: 'Regular' },
    { name: '122', type: 'Bus', subtype: 'Regular' },
    { name: '124', type: 'Bus', subtype: 'Regular' },
    { name: '125', type: 'Bus', subtype: 'Regular' },
    { name: '126', type: 'Bus', subtype: 'Regular' },
    { name: '127', type: 'Bus', subtype: 'Regular' },
    { name: '128', type: 'Bus', subtype: 'Regular' },
    { name: '129', type: 'Bus', subtype: 'Regular' },
    { name: '130', type: 'Bus', subtype: 'Regular' },
    { name: '131', type: 'Bus', subtype: 'Regular' },
    { name: '132', type: 'Bus', subtype: 'Regular' },
    { name: '133', type: 'Bus', subtype: 'Regular' },
    { name: '134', type: 'Bus', subtype: 'Regular' },
    { name: '136', type: 'Bus', subtype: 'Regular' },
    { name: '140', type: 'Bus', subtype: 'Regular' },
    { name: '141', type: 'Bus', subtype: 'Regular' },
    { name: '142', type: 'Bus', subtype: 'Regular' },
    { name: '143', type: 'Bus', subtype: 'Regular' },
    { name: '144', type: 'Bus', subtype: 'Regular' },
    { name: '145', type: 'Bus', subtype: 'Regular' },
    { name: '146', type: 'Bus', subtype: 'Regular' },
    { name: '147', type: 'Bus', subtype: 'Regular' },
    { name: '148', type: 'Bus', subtype: 'Regular' },
    { name: '149', type: 'Bus', subtype: 'Regular' },
    { name: '150', type: 'Bus', subtype: 'Regular' },
    { name: '151', type: 'Bus', subtype: 'Regular' },
    { name: '206', type: 'Bus', subtype: 'Night' },
    { name: '240', type: 'Bus', subtype: 'Night' },
    { name: '241', type: 'Bus', subtype: 'Night' },
    { name: '242', type: 'Bus', subtype: 'Night' },
    { name: '243', type: 'Bus', subtype: 'Night' },
    { name: '245', type: 'Bus', subtype: 'Night' },
    { name: '246', type: 'Bus', subtype: 'Night' },
    { name: '247', type: 'Bus', subtype: 'Night' },
    { name: '248', type: 'Bus', subtype: 'Night' },
    { name: '249', type: 'Bus', subtype: 'Night' },
    { name: '250', type: 'Bus', subtype: 'Night' },
    { name: '251', type: 'Bus', subtype: 'Night' },
    { name: '253', type: 'Bus', subtype: 'Night' },
    { name: '255', type: 'Bus', subtype: 'Night' },
    { name: '257', type: 'Bus', subtype: 'Night' },
    { name: '259', type: 'Bus', subtype: 'Night' },
    { name: '319', type: 'Bus', subtype: 'Regular' },
    { name: '325', type: 'Bus', subtype: 'Regular' },
    { name: '602', type: 'Bus', subtype: 'Suburban' },
    { name: '607', type: 'Bus', subtype: 'Suburban' },
    { name: '609', type: 'Bus', subtype: 'Suburban' },
    { name: '612', type: 'Bus', subtype: 'Suburban' }
  ];
}
