import { Line } from '../models';
import { LinesProvider } from './LinesProvider';
import { Timestamped } from '../models';

export class DummyLineProvider implements LinesProvider {

  getLines(): Promise<Timestamped<Line[]>> {
    const timestamp = new Date().toISOString();
    const data = DummyLineProvider.data;
    return Promise.resolve({ timestamp, data });
  }

  static data: Line[] = [
    DummyLineProvider.createLine('A', 'Bus', 'Express'),
    DummyLineProvider.createLine('C', 'Bus', 'Express'),
    DummyLineProvider.createLine('D', 'Bus', 'Express'),
    DummyLineProvider.createLine('K', 'Bus', 'Express'),
    DummyLineProvider.createLine('N', 'Bus', 'Express'),
    DummyLineProvider.createLine('0P', 'Tram', 'Regular'),
    DummyLineProvider.createLine('0L', 'Tram', 'Regular'),
    DummyLineProvider.createLine('1', 'Tram', 'Regular'),
    DummyLineProvider.createLine('2', 'Tram', 'Regular'),
    DummyLineProvider.createLine('3', 'Tram', 'Regular'),
    DummyLineProvider.createLine('4', 'Tram', 'Regular'),
    DummyLineProvider.createLine('5', 'Tram', 'Regular'),
    DummyLineProvider.createLine('6', 'Tram', 'Regular'),
    DummyLineProvider.createLine('7', 'Tram', 'Regular'),
    DummyLineProvider.createLine('8', 'Tram', 'Regular'),
    DummyLineProvider.createLine('9', 'Tram', 'Regular'),
    DummyLineProvider.createLine('10', 'Tram', 'Regular'),
    DummyLineProvider.createLine('11', 'Tram', 'Regular'),
    DummyLineProvider.createLine('15', 'Tram', 'Regular'),
    DummyLineProvider.createLine('16', 'Tram', 'Regular'),
    DummyLineProvider.createLine('17', 'Tram', 'Regular'),
    DummyLineProvider.createLine('20', 'Tram', 'Regular'),
    DummyLineProvider.createLine('23', 'Tram', 'Regular'),
    DummyLineProvider.createLine('31', 'Tram', 'Regular'),
    DummyLineProvider.createLine('32', 'Tram', 'Regular'),
    DummyLineProvider.createLine('33', 'Tram', 'Regular'),
    DummyLineProvider.createLine('100', 'Bus', 'Regular'),
    DummyLineProvider.createLine('101', 'Bus', 'Regular'),
    DummyLineProvider.createLine('102', 'Bus', 'Regular'),
    DummyLineProvider.createLine('103', 'Bus', 'Regular'),
    DummyLineProvider.createLine('104', 'Bus', 'Regular'),
    DummyLineProvider.createLine('105', 'Bus', 'Regular'),
    DummyLineProvider.createLine('106', 'Bus', 'Regular'),
    DummyLineProvider.createLine('107', 'Bus', 'Regular'),
    DummyLineProvider.createLine('108', 'Bus', 'Regular'),
    DummyLineProvider.createLine('109', 'Bus', 'Regular'),
    DummyLineProvider.createLine('110', 'Bus', 'Regular'),
    DummyLineProvider.createLine('111', 'Bus', 'Regular'),
    DummyLineProvider.createLine('112', 'Bus', 'Regular'),
    DummyLineProvider.createLine('113', 'Bus', 'Regular'),
    DummyLineProvider.createLine('114', 'Bus', 'Regular'),
    DummyLineProvider.createLine('115', 'Bus', 'Regular'),
    DummyLineProvider.createLine('116', 'Bus', 'Regular'),
    DummyLineProvider.createLine('118', 'Bus', 'Regular'),
    DummyLineProvider.createLine('119', 'Bus', 'Regular'),
    DummyLineProvider.createLine('120', 'Bus', 'Regular'),
    DummyLineProvider.createLine('121', 'Bus', 'Regular'),
    DummyLineProvider.createLine('122', 'Bus', 'Regular'),
    DummyLineProvider.createLine('124', 'Bus', 'Regular'),
    DummyLineProvider.createLine('125', 'Bus', 'Regular'),
    DummyLineProvider.createLine('126', 'Bus', 'Regular'),
    DummyLineProvider.createLine('127', 'Bus', 'Regular'),
    DummyLineProvider.createLine('128', 'Bus', 'Regular'),
    DummyLineProvider.createLine('129', 'Bus', 'Regular'),
    DummyLineProvider.createLine('130', 'Bus', 'Regular'),
    DummyLineProvider.createLine('131', 'Bus', 'Regular'),
    DummyLineProvider.createLine('132', 'Bus', 'Regular'),
    DummyLineProvider.createLine('133', 'Bus', 'Regular'),
    DummyLineProvider.createLine('134', 'Bus', 'Regular'),
    DummyLineProvider.createLine('136', 'Bus', 'Regular'),
    DummyLineProvider.createLine('140', 'Bus', 'Regular'),
    DummyLineProvider.createLine('141', 'Bus', 'Regular'),
    DummyLineProvider.createLine('142', 'Bus', 'Regular'),
    DummyLineProvider.createLine('143', 'Bus', 'Regular'),
    DummyLineProvider.createLine('144', 'Bus', 'Regular'),
    DummyLineProvider.createLine('145', 'Bus', 'Regular'),
    DummyLineProvider.createLine('146', 'Bus', 'Regular'),
    DummyLineProvider.createLine('147', 'Bus', 'Regular'),
    DummyLineProvider.createLine('148', 'Bus', 'Regular'),
    DummyLineProvider.createLine('149', 'Bus', 'Regular'),
    DummyLineProvider.createLine('150', 'Bus', 'Regular'),
    DummyLineProvider.createLine('151', 'Bus', 'Regular'),
    DummyLineProvider.createLine('206', 'Bus', 'Night'),
    DummyLineProvider.createLine('240', 'Bus', 'Night'),
    DummyLineProvider.createLine('241', 'Bus', 'Night'),
    DummyLineProvider.createLine('242', 'Bus', 'Night'),
    DummyLineProvider.createLine('243', 'Bus', 'Night'),
    DummyLineProvider.createLine('245', 'Bus', 'Night'),
    DummyLineProvider.createLine('246', 'Bus', 'Night'),
    DummyLineProvider.createLine('247', 'Bus', 'Night'),
    DummyLineProvider.createLine('248', 'Bus', 'Night'),
    DummyLineProvider.createLine('249', 'Bus', 'Night'),
    DummyLineProvider.createLine('250', 'Bus', 'Night'),
    DummyLineProvider.createLine('251', 'Bus', 'Night'),
    DummyLineProvider.createLine('253', 'Bus', 'Night'),
    DummyLineProvider.createLine('255', 'Bus', 'Night'),
    DummyLineProvider.createLine('257', 'Bus', 'Night'),
    DummyLineProvider.createLine('259', 'Bus', 'Night'),
    DummyLineProvider.createLine('319', 'Bus', 'Regular'),
    DummyLineProvider.createLine('325', 'Bus', 'Regular'),
    DummyLineProvider.createLine('602', 'Bus', 'Suburban'),
    DummyLineProvider.createLine('607', 'Bus', 'Suburban'),
    DummyLineProvider.createLine('609', 'Bus', 'Suburban'),
    DummyLineProvider.createLine('612', 'Bus', 'Suburban')
  ];

  static createLine(name: string, type: string, subtype: string): Line {
    return {
      name,
      type,
      subtype,
      stopArrivalTimes: undefined
    }
  }
}
