import { Tweet, parse } from "../parse";
import { TwitterUser } from "../../TwitterClient";

describe("Nitter-parse", () => {
  it("caches user on 1st call", async () => {
    const xml = `
    <?xml version="1.0" encoding="UTF-8"?>
    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
      <channel>
        <atom:link href="https://nitter.privacydev.net/AlertMPK/rss" rel="self" type="application/rss+xml" />
        <title>MPK Wrocław / @AlertMPK</title>
        <link>https://nitter.privacydev.net/AlertMPK</link>
        <description>Twitter feed for: @AlertMPK. Generated by nitter.privacydev.net
    </description>
        <language>en-us</language>
        <ttl>40</ttl>
        <image>
          <title>MPK Wrocław / @AlertMPK</title>
          <link>https://nitter.privacydev.net/AlertMPK</link>
          <url>https://nitter.privacydev.net/pic/pbs.twimg.com%2Fprofile_images%2F676359617211998208%2Fq015WWtC_400x400.jpg</url>
          <width>128</width>
          <height>128</height>
        </image>
          <item>
            <title>#AlertMPK ul. Kazimierza Wielkiego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Kazimierza Wielkiego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Tue, 30 Apr 2024 06:29:15 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1785194688678404482#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1785194688678404482#m</link>
          </item>
          <item>
            <title>#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Kazimierza Wielkiego (awaria tramwaju).
🚋 Tramwaje linii 3, 10, 12, 13 i 18 kursujące w kierunku pl. Dominikańskiego zostały skierowane objazdem przez ul. Krupnicza, Podwale, Teatralną.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23TRAM">#TRAM</a><br>
⚠️ Brak przejazdu - ul. Kazimierza Wielkiego (awaria tramwaju).<br>
🚋 Tramwaje linii 3, 10, 12, 13 i 18 kursujące w kierunku pl. Dominikańskiego zostały skierowane objazdem przez ul. Krupnicza, Podwale, Teatralną.</p>]]></description>
            <pubDate>Tue, 30 Apr 2024 06:10:15 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1785189907868098826#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1785189907868098826#m</link>
          </item>
          <item>
            <title>#AlertMPK pętla Osiedle Sobieskiego - ruch przywrócony. Autobusy wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> pętla Osiedle Sobieskiego - ruch przywrócony. Autobusy wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 16:03:33 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783889664077627491#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783889664077627491#m</link>
          </item>
          <item>
            <title>#AlertMPK #BUS
⚠️ Brak przejazdu - pętla Osiedle Sobieskiego
🚍 Autobusy linii D, 111 i 130 kursują do pętli Zakrzów.
🚍 Kursowanie autobusów linii 150 zostało skrócone do Ronda Lotników Polskich.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23BUS">#BUS</a><br>
⚠️ Brak przejazdu - pętla Osiedle Sobieskiego<br>
🚍 Autobusy linii D, 111 i 130 kursują do pętli Zakrzów.<br>
🚍 Kursowanie autobusów linii 150 zostało skrócone do Ronda Lotników Polskich.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 15:21:14 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783879014865678519#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783879014865678519#m</link>
          </item>
          <item>
            <title>#AlertMPK ul. Świeradowska - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Świeradowska - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 14:10:27 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783861200704377169#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783861200704377169#m</link>
          </item>
          <item>
            <title>R to @AlertMPK: AKTUALIZACJA 16:04
🚍 Zadysponowano zastępczą komunikację autobusową w relacji Bardzka - Gaj - Bardzka.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p>AKTUALIZACJA 16:04<br>
🚍 Zadysponowano zastępczą komunikację autobusową w relacji Bardzka - Gaj - Bardzka.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 14:05:16 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783859896913396069#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783859896913396069#m</link>
          </item>
          <item>
            <title>#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Świeradowska (pomoc medyczna dla pasażera).
🚋 Tramwaje linii 18 i 21 zostały skierowane objazdem w obu kierunkach do pętli Tarnogaj.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23TRAM">#TRAM</a><br>
⚠️ Brak przejazdu - ul. Świeradowska (pomoc medyczna dla pasażera).<br>
🚋 Tramwaje linii 18 i 21 zostały skierowane objazdem w obu kierunkach do pętli Tarnogaj.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 13:57:33 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783857954699067856#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783857954699067856#m</link>
          </item>
          <item>
            <title>#AlertMPK ul. Piłsudskiego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Piłsudskiego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 13:45:08 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783854830932447569#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783854830932447569#m</link>
          </item>
          <item>
            <title>R to @AlertMPK: Przystanek &quot;pl. Orląt Lwowskich&quot; realizowany jest na ul. Podwale.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p>Przystanek "pl. Orląt Lwowskich" realizowany jest na ul. Podwale.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 13:39:24 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783853387269673144#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783853387269673144#m</link>
          </item>
          <item>
            <title>#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Piłsudskiego (pomoc medyczna dla pasażera).
🚋 Tramwaje linii 14&gt;Krzyki, 15&gt;Park Południowy 21&gt;Gaj, 22&gt;Tarnogaj i 23&gt;Kowale realizują przystanek &quot;Plac Legionów&quot; przy ul. Sądowej.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23TRAM">#TRAM</a> <br>
⚠️ Brak przejazdu - ul. Piłsudskiego (pomoc medyczna dla pasażera).<br>
🚋 Tramwaje linii 14&gt;Krzyki, 15&gt;Park Południowy 21&gt;Gaj, 22&gt;Tarnogaj i 23&gt;Kowale realizują przystanek "Plac Legionów" przy ul. Sądowej.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 13:33:19 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783851856638115938#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783851856638115938#m</link>
          </item>
          <item>
            <title>#AlertMPK ul. Szczytnicka - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Szczytnicka - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 12:31:37 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783836329186607186#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783836329186607186#m</link>
          </item>
          <item>
            <title>#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Szczytnicka (akcja Pogotowia Ratunkowego w obrębie torowiska).
🚋 Tramwaje linii 2 i 10&gt;Biskupin zostały skierowane objazdem przez most Grunwaldzki.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23TRAM">#TRAM</a><br>
⚠️ Brak przejazdu - ul. Szczytnicka (akcja Pogotowia Ratunkowego w obrębie torowiska).<br>
🚋 Tramwaje linii 2 i 10&gt;Biskupin zostały skierowane objazdem przez most Grunwaldzki.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 12:26:10 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783834955103281561#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783834955103281561#m</link>
          </item>
          <item>
            <title>#AlertMPK ul. Hubska - ruch przywrócony. Tramwaje i autobusy wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Hubska - ruch przywrócony. Tramwaje i autobusy wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 11:02:17 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783813845892350001#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783813845892350001#m</link>
          </item>
          <item>
            <title>#AlertMPK ul. Pomorska - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Pomorska - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 10:15:07 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783801976645390446#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783801976645390446#m</link>
          </item>
          <item>
            <title>R to @AlertMPK: AKTUALIZACJA 11:07
🚋 Tramwaje linii 18 wróciły na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p>AKTUALIZACJA 11:07<br>
🚋 Tramwaje linii 18 wróciły na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 09:08:53 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783785309009777007#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783785309009777007#m</link>
          </item>
          <item>
            <title>R to @AlertMPK: AKTUALIZACJA 10:55
🚋 Tramwaje linii 19&gt;ZOO zostały skierowane przez most Sikorskiego, pl. Jana Pawła II, ul. Kazimierza Wielkiego, Szewską, Grodzką, most Uniwersytecki.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p>AKTUALIZACJA 10:55<br>
🚋 Tramwaje linii 19&gt;ZOO zostały skierowane przez most Sikorskiego, pl. Jana Pawła II, ul. Kazimierza Wielkiego, Szewską, Grodzką, most Uniwersytecki.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 08:58:51 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783782784193921102#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783782784193921102#m</link>
          </item>
          <item>
            <title>R to @AlertMPK: AKTUALIZACJA 10:55
🚋 Tramwaje linii 14&gt;Dworzec Nadodrze, 15&gt;Poświętne zostały skierowane przez ul. Sądową, Krupniczą, Kazimierza Wielkiego, Szewską, Grodzką, most Uniwersytecki.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p>AKTUALIZACJA 10:55<br>
🚋 Tramwaje linii 14&gt;Dworzec Nadodrze, 15&gt;Poświętne zostały skierowane przez ul. Sądową, Krupniczą, Kazimierza Wielkiego, Szewską, Grodzką, most Uniwersytecki.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 08:58:50 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783782781102805044#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783782781102805044#m</link>
          </item>
          <item>
            <title>#AlertMPK #TRAM
⚠️ Brak przejazdu ul. Pomorska (awaria zwrotnicy).
🚋 Tramwaje linii 18&gt;Gaj skierowano od przystanku Pomorska przez ul. Dubois, most Uniwersytecki, ul. Grodzką.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23TRAM">#TRAM</a><br>
⚠️ Brak przejazdu ul. Pomorska (awaria zwrotnicy).<br>
🚋 Tramwaje linii 18&gt;Gaj skierowano od przystanku Pomorska przez ul. Dubois, most Uniwersytecki, ul. Grodzką.</p>]]></description>
            <pubDate>Fri, 26 Apr 2024 08:39:54 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783778015865909603#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783778015865909603#m</link>
          </item>
          <item>
            <title>#AlertMPK ul. Chrobrego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> ul. Chrobrego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu.</p>]]></description>
            <pubDate>Thu, 25 Apr 2024 19:02:52 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783572400593940714#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783572400593940714#m</link>
          </item>
          <item>
            <title>#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Chrobrego (akcja Pogotowia Ratunkowego w obrębie torowiska).
🚋 Tramwaje linii 7&gt;Klecina, 14&gt;Krzyki i 15&gt;Park Południowy zostały skierowane objazdem przez ul. Słowiańską, Jedności Narodowej, pl. Bema, ul. Drobnera.</title>
            <dc:creator>@AlertMPK</dc:creator>
            <description><![CDATA[<p><a href="https://nitter.privacydev.net/search?q=%23AlertMPK">#AlertMPK</a> <a href="https://nitter.privacydev.net/search?q=%23TRAM">#TRAM</a><br>
⚠️ Brak przejazdu - ul. Chrobrego (akcja Pogotowia Ratunkowego w obrębie torowiska).<br>
🚋 Tramwaje linii 7&gt;Klecina, 14&gt;Krzyki i 15&gt;Park Południowy zostały skierowane objazdem przez ul. Słowiańską, Jedności Narodowej, pl. Bema, ul. Drobnera.</p>]]></description>
            <pubDate>Thu, 25 Apr 2024 19:01:37 GMT</pubDate>
            <guid>https://nitter.privacydev.net/AlertMPK/status/1783572089561084293#m</guid>
            <link>https://nitter.privacydev.net/AlertMPK/status/1783572089561084293#m</link>
          </item>

      </channel>
    </rss>
    `;

    const user = new TwitterUser("MPK Wrocław", "AlertMPK");
    const maxCount = 20;
    const result = await parse(xml, user, maxCount);

    expect(result).toEqual({
      kind: "Success",
      tweets: [
        new Tweet(
          "83e1684724fc9d3ef45fa2c2967b3bf2af37bfde40ff554d30cceae398f1c9cb",
          user,
          new Date("2024-04-30T06:29:15.000Z"),
          "#AlertMPK ul. Kazimierza Wielkiego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "3b865b6094a2c209c553d25c6d40ba39f0b805caaec6364dc5938087b7cbf442",
          user,
          new Date("2024-04-30T06:10:15.000Z"),
          `#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Kazimierza Wielkiego (awaria tramwaju).
🚋 Tramwaje linii 3, 10, 12, 13 i 18 kursujące w kierunku pl. Dominikańskiego zostały skierowane objazdem przez ul. Krupnicza, Podwale, Teatralną.`
        ),
        new Tweet(
          "fdec411b3f829b79f68f9030538104a6b2dbed6e8ba2f1f44456020378e4fa8b",
          user,
          new Date("2024-04-26T16:03:33.000Z"),
          "#AlertMPK pętla Osiedle Sobieskiego - ruch przywrócony. Autobusy wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "d27fd4430e50f3148fafc649deb1feced406ec297466559546299c6672fd2971",
          user,
          new Date("2024-04-26T15:21:14.000Z"),
          `#AlertMPK #BUS
⚠️ Brak przejazdu - pętla Osiedle Sobieskiego
🚍 Autobusy linii D, 111 i 130 kursują do pętli Zakrzów.
🚍 Kursowanie autobusów linii 150 zostało skrócone do Ronda Lotników Polskich.`
        ),
        new Tweet(
          "fc8bc3f30b52de124e005ab51c0c41a4278736f71e25b902c6c98d461ddd9e84",
          user,
          new Date("2024-04-26T14:10:27.000Z"),
          "#AlertMPK ul. Świeradowska - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "936fd5c53aa00f77cfe065c3bb8e0cdf99314672fd93fea5e1c09d265569348e",
          user,
          new Date("2024-04-26T14:05:16.000Z"),
          `AKTUALIZACJA 16:04
🚍 Zadysponowano zastępczą komunikację autobusową w relacji Bardzka - Gaj - Bardzka.`
        ),
        new Tweet(
          "9eb4ec8db6e172015f334dd87fbfe82fd0b2fd119002edd3f25e93adb6a75caa",
          user,
          new Date("2024-04-26T13:57:33.000Z"),
          `#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Świeradowska (pomoc medyczna dla pasażera).
🚋 Tramwaje linii 18 i 21 zostały skierowane objazdem w obu kierunkach do pętli Tarnogaj.`
        ),
        new Tweet(
          "97503a602bcdb109d27af4490065b3313cebcf61c35951e27a86ef70df6d5e59",
          user,
          new Date("2024-04-26T13:45:08.000Z"),
          "#AlertMPK ul. Piłsudskiego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "f6610ff0f13215e145c3d920400952b5831722b79bc4bf214cbb883948931b1b",
          user,
          new Date("2024-04-26T13:39:24.000Z"),
          'Przystanek "pl. Orląt Lwowskich" realizowany jest na ul. Podwale.'
        ),
        new Tweet(
          "c8788f4d5a8a0ac96c8adffa48811e62b2b5a0c43a65f6e02d3eac36c70b65f3",
          user,
          new Date("2024-04-26T13:33:19.000Z"),
          `#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Piłsudskiego (pomoc medyczna dla pasażera).
🚋 Tramwaje linii 14>Krzyki, 15>Park Południowy 21>Gaj, 22>Tarnogaj i 23>Kowale realizują przystanek \"Plac Legionów\" przy ul. Sądowej.`
        ),
        new Tweet(
          "7c662ab1aa7cc2b013b9c586a4cba04741fc596be1956693822bc93e6a3f502b",
          user,
          new Date("2024-04-26T12:31:37.000Z"),
          "#AlertMPK ul. Szczytnicka - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "45b625dffba1d126cace2c6845c90eb9d98deb3760e4fa75889c3e91eb07475f",
          user,
          new Date("2024-04-26T12:26:10.000Z"),
          `#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Szczytnicka (akcja Pogotowia Ratunkowego w obrębie torowiska).
🚋 Tramwaje linii 2 i 10>Biskupin zostały skierowane objazdem przez most Grunwaldzki.`
        ),
        new Tweet(
          "c1da1d2b1d02cf6527ec75ec9ca4278e141f825f22d9a9c1fffbd2a19f878459",
          user,
          new Date("2024-04-26T11:02:17.000Z"),
          "#AlertMPK ul. Hubska - ruch przywrócony. Tramwaje i autobusy wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "4402dbddb26ed6953c05429c6b230d7471bcc080c1ba15f14445f41df8327245",
          user,
          new Date("2024-04-26T10:15:07.000Z"),
          "#AlertMPK ul. Pomorska - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "7d86fd62c5b0cf8550cf9f07bca3ea21a17d60981ae1f20059f5503ba1ed9ef0",
          user,
          new Date("2024-04-26T09:08:53.000Z"),
          `AKTUALIZACJA 11:07
🚋 Tramwaje linii 18 wróciły na swoje stałe trasy przejazdu.`
        ),
        new Tweet(
          "1688b4b1d18519e4c4b17fae9a3f580bcce0d76eec742dde844ae0cc94e9a2a9",
          user,
          new Date("2024-04-26T08:58:51.000Z"),
          `AKTUALIZACJA 10:55
🚋 Tramwaje linii 19>ZOO zostały skierowane przez most Sikorskiego, pl. Jana Pawła II, ul. Kazimierza Wielkiego, Szewską, Grodzką, most Uniwersytecki.`
        ),
        new Tweet(
          "1c12938bbb42582c58373f9b005d115d834da78146ab8c84a75f5c47e9e9f30c",
          user,
          new Date("2024-04-26T08:58:50.000Z"),
          `AKTUALIZACJA 10:55
🚋 Tramwaje linii 14>Dworzec Nadodrze, 15>Poświętne zostały skierowane przez ul. Sądową, Krupniczą, Kazimierza Wielkiego, Szewską, Grodzką, most Uniwersytecki.`
        ),
        new Tweet(
          "92ce2bf67ad4bb733efcdc9aa3f5962d05dc182519b6427f1068cee0b1e77fdf",
          user,
          new Date("2024-04-26T08:39:54.000Z"),
          `#AlertMPK #TRAM
⚠️ Brak przejazdu ul. Pomorska (awaria zwrotnicy).
🚋 Tramwaje linii 18>Gaj skierowano od przystanku Pomorska przez ul. Dubois, most Uniwersytecki, ul. Grodzką.`
        ),
        new Tweet(
          "756a32de0a351eea2fbaf6da4109de3a23b905dfcb8c4a39e074b3d3472a5ce5",
          user,
          new Date("2024-04-25T19:02:52.000Z"),
          "#AlertMPK ul. Chrobrego - ruch przywrócony. Tramwaje wracają na swoje stałe trasy przejazdu."
        ),
        new Tweet(
          "29d47e93fe487038363c0d653003cce8fc6eae653931571316c10ed32f6343cc",
          user,
          new Date("2024-04-25T19:01:37.000Z"),
          `#AlertMPK #TRAM
⚠️ Brak przejazdu - ul. Chrobrego (akcja Pogotowia Ratunkowego w obrębie torowiska).
🚋 Tramwaje linii 7>Klecina, 14>Krzyki i 15>Park Południowy zostały skierowane objazdem przez ul. Słowiańską, Jedności Narodowej, pl. Bema, ul. Drobnera.`
        ),
      ],
    });

    console.log();
  });
});
